spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weather_service_db
    username: postgres
    password: postgres
